services:
  gsender2mqtt:
    build: .
    environment:
      - SERVERURL=http://192.168.12.195:8000
      - MQTTSERVER=192.168.1.1
      - MQTTPORT=1883
      - MQTTUSERNAME=
      - MQTTPASSWORD=
      - MQTTTOPIC=gsender
      - MQTTCLIENTID=gsender2mqtt
      - RETRYDELAY=60000
      - INCLUDEWORKFLOW=true