services:
  gsender2mqtt:
    build: .
    environment:
      - SERVERURL=http://localhost:8000
      - GRBLHALIPADDRESS=192.168.1.100
      - MQTTSERVER=localhost
      - MQTTPORT=1883
      - MQTTUSERNAME=
      - MQTTPASSWORD=
      - MQTTTOPIC=gsender
      - MQTT_EMIT_TOPIC=gsender/emit
      - MQTTCLIENTID=gsender2mqtt
      - RETRYDELAY=60000