services:
  gsender2mqtt:
    build: .
    environment:
      - SERVERURL=http://localhost:8000
      - MQTTSERVER=localhost
      - MQTTPORT=1883
      - MQTTUSERNAME=
      - MQTTPASSWORD=
      - MQTTTOPIC=gsender
      - MQTTCLIENTID=gsender2mqtt
      - RETRYDELAY=60000